### ISSUE TITLE
Multiple `once` listeners receive the same message twice

### ISSUE THREAD

**Issue by vprufus7** [OmniacDev/MCBE-IPC#3]
When I create 2 `once` listeners to the same channel like so:
```ts
  IPC.once("test", (message) => {
    console.log("first once", JSON.stringify(message));
  });
  IPC.once("test", (message) => {
    console.log("second once", JSON.stringify(message));
  });

  IPC.send("test", { hello: "world" });
  IPC.send("test", { hello: "world2" });

```

Each listener is called one time (as I would expect), but they both receive the first message:
```
[2024-08-28 09:03:38:828 INFO] [Scripting] first once {"hello":"world"}

[2024-08-28 09:03:38:828 INFO] [Scripting] second once {"hello":"world"}
```

I would expect that the first `once` handler would have gotten the first message and the second handler would have gotten the second message.

**Comment by OmniacDev** [comment]
`once` will subscribe to the event whenever it's called, so in your example they are behaving as intended; both subscribe at the same time, so they will both fire at the same time. 

If you wanted to stagger them after each other, you could do something like this:
```ts
  IPC.once("test", (message) => {
    console.log("first once", JSON.stringify(message));
    
    IPC.once("test", (message) => {
      console.log("second once", JSON.stringify(message));
    });
  });
  

  IPC.send("test", { hello: "world" });
  IPC.send("test", { hello: "world2" });
```

This will subscribe the to the next event, after the first one has fired.

**Comment by vprufus7** [comment]
That makes sense. Thanks!
